### ISSUE TITLE
DynaFile is coupled to Maven.

### ISSUE THREAD

**Issue by aleixmorgadas** [vlingo/vlingo-common#4]
https://github.com/vlingo/vlingo-common/blob/master/src/main/java/io/vlingo/common/compiler/DynaFile.java#L14-L17

Gradle generate the classes in another folder, like `out/production/classes`. It causes vlingo to just be compatible to Maven projects.

**Comment by aleixmorgadas** [comment]
I opened the issue because, indeed, it hasn't worked on Gradle for
development. I was sure it works on release mode.

I could create a repository with an example Gradle project if it helps.
Maybe I missed something, but I created the project with Maven to be sure
it was due to Gradle.

Let me know if you need more information, like versioning, about this issue.

**Comment by VaughnVernon** [comment]
I have found it very difficult to locate an explicit generated source location for Gradle or how to determine at runtime which environment is in use. I could use help here, if even making it a configuration.

**Comment by d-led** [comment]
That would be indeed helpful to know which context you are talking about exactly, e.g. IntellJ or Eclipse and what difference you mean between release and development. Just [bumped the vlingo-actors version](https://github.com/d-led/hello_vlingo/commit/e049a18e110a3287d9fc05eb2ba49229784dcedc) to see if it still works. It does: https://travis-ci.org/d-led/hello_vlingo/builds/404155607

**Comment by d-led** [comment]
@aleixmorgadas it would be nice if you could set up an example project that could be to debug

**Comment by aleixmorgadas** [comment]
I create the [vlingo-http-gradle-issue-4](https://github.com/aleixmorgadas/vlingo-http-gradle-issue-4) repository with the minimum code to throw the error. 

The IDE used is IntelliJ & I started the application in the same IDE. The same structure with Maven works.

**Comment by VaughnVernon** [comment]
@aleixmorgadas Thanks for the stack trace and sample project. I have struggled to find anything specific in Gradle docs and various forum discussions regarding where generated source should be located. Can you make a recommendation based on your experience with Gradle and IntelliJ? My thought is to provide a configuration root for both main and test. The following is an example for vlingo-http.properties, or would be included in your DSL configuration. Please provide your thoughts.

```#=====================================
# generated resource handlers
#=====================================

resource.dispatcher.generated.source.main  = target/generated-sources/
resource.dispatcher.generated.source.test  = target/generated-test-sources/
resource.dispatcher.generated.classes.main = target/classes/
resource.dispatcher.generated.classes.test = target/test-classes/```

**Comment by VaughnVernon** [comment]
@aleixmorgadas @d-led I implemented this as I stated above. It's all pushed to vlingo-actors master and vlingo-http master. Here are the two sets of configurations:

```
# vlingo-actors.properties
proxy.generated.sources.main = target/generated-sources/
proxy.generated.sources.test = target/generated-test-sources/
proxy.generated.classes.main = target/classes/
proxy.generated.classes.test = target/test-classes/
----------------------------
# vlingo-http.properties
resource.dispatcher.generated.sources.main = target/generated-sources/
resource.dispatcher.generated.sources.test = target/generated-test-sources/
resource.dispatcher.generated.classes.main = target/classes/
resource.dispatcher.generated.classes.test = target/test-classes/
```

**Comment by aleixmorgadas** [comment]
Checked. Working with the latest version `0.4.0`

**Comment by VaughnVernon** [comment]
@aleixmorgadas Thanks. I answer your questions here.

1. We don't require runtime code generation and compilation unless the developer has not arranged for proxies to be pre-generated. For `vlingo-actors` you can use the `vlingo-maven-plugin`. See the `vlingo-maven-plugin-test` for usage. For `vlingo-http` the `vlingo-maven-plugin` has not yet been enabled for dispatcher proxy generation support.

2. There are configuration files now, but very minimal configuration is required. It has always been my intention to support fluent configuration APIs, but right now I am focused on important features/functionality. As you can see most of the projects are at `0.5.0` or less. This is something that developers of the tools should be willing to work with for a short time until there is time to make it more seamless. _If you can't live with that right now for some reason please change it._

3. The configuration is minimal, and in *vlingo-actors* there is no consumer-programmer configuration necessary for reasonable default behavior (remove `vlingo-actors.properties` and see). Yes, current default behavior for proxy generation is for Maven, not Gradle, but it's simple to understand why when considering overall industry usage of Maven. It's not a judgment as to which is better, it's just numbers of projects/users.
