### ISSUE TITLE
please update vlingo-common in repository

### ISSUE THREAD

**Issue by wevogt** [vlingo/vlingo-common#8]
There is a code-extension, class io.vlingo.common.Tuple4, which ist not updated in maven-repository, version 0-74 (not in sync).
This will cause an error in vlingo-examples.

Thanks

**Comment by VaughnVernon** [comment]
Hi @wevogt Thanks for reporting. This has been fixed with `0.7.5` release on 17 December. If you will please, confirm the fix and close this Issue. Thanks again!

**Comment by wevogt** [comment]
Well done, thanks
